============================
Tests for BaseGeometry class
============================

Importing BaseGeometry
======================

>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

Correct values
==============

>>> bg = BaseGeometry()

>>> bg.integer_validator("my_int", int("12"))

>>> bg.integer_validator("width", 89**998172)

Exceptions
==========

>>> bg.integer_validator("val", float("Nan"))
Traceback (most recent call last):
    ...Traceback...
TypeError: val must be an integer

>>> bg.integer_validator("val", 4.5)
Traceback (most recent call last):
    ...Traceback...
TypeError: val must be an integer

>>> bg.integer_validator("val", [7])
Traceback (most recent call last):
    ...Traceback...
TypeError: val must be an integer

>>> bg.integer_validator("val", True)
Traceback (most recent call last):
    ...Traceback...
TypeError: val must be an integer

>>> bg.integer_validator("val", "49")
Traceback (most recent call last):
    ...Traceback...
TypeError: val must be an integer

>>> bg.integer_validator("val", {"49": 1})
Traceback (most recent call last):
    ...Traceback...
TypeError: val must be an integer

>>> bg.integer_validator("val", (23,))
Traceback (most recent call last):
    ...Traceback...
TypeError: val must be an integer

>>> bg.integer_validator("val", None)
Traceback (most recent call last):
    ...Traceback...
TypeError: val must be an integer

>>> bg.integer_validator("val", bg.integer_validator)
Traceback (most recent call last):
    ...Traceback...
TypeError: val must be an integer

>>> bg.integer_validator("int", 0)
Traceback (most recent call last):
    ...Traceback...
ValueError: int must be greater than 0

>>> bg.integer_validator("length", -25)
Traceback (most recent call last):
    ...Traceback...
ValueError: length must be greater than 0

>>> bg.area()
Traceback (most recent call last):
    ...Traceback...
Exception: area() is not implemented

>>> bg.integer_validator("int")
Traceback (most recent call last):
    ...Traceback...
TypeError: integer_validator() missing 1 required positional argument: 'value'

>>> bg.integer_validator()
Traceback (most recent call last):
    ...Traceback...
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'
